module.exports = {
    ADMIN: require("./admin.constants"),
    AUTH: require("./auth.constants"),
    USER: require("./user.constants"),
    ORDER: require("./order.constants"),
    PRODUCT: require("./product.constants"),
    SHOP: require("./shop.constants"),
    MESSAGES: require("./messages.constants"),
    HTTP_STATUS: require("./httpStatus.constants"),
    RABBIT_QUEUE: require("./rabbitmq.constants"),
    REDIS: require("./redis.constants"),
    STATUS: require("./status.constants"),
    SOCKET: require("./socket.constant"),
    ACTIVITY_LOG: require("./activityLog.constants"),
    CART: require("./cart.constants"),
    RESERVATION_LOG: require("./reservationLog.constants"),
};
