version: '3.8'

services:
  # 1. APP BACKEND (Của team bạn)
  backend:
    build: .
    container_name: flashsale_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # 👇 SỬA LẠI CHO KHỚP VỚI TÊN SERVICE BÊN DƯỚI
      - MONGO_URI=mongodb://mongodb:27017/flashsale 
      - REDIS_URI=redis://redis:6379
      - RABBITMQ_URI=amqp://rabbitmq:5672
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - flashsale-network

  # 2. Database MongoDB
  mongodb: # Tên service là mongodb
    image: mongo:latest
    container_name: flashsale_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - flashsale-network

  # 3. Redis
  redis: # Tên service là redis
    image: redis:alpine
    container_name: flashsale_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - flashsale-network

  # 4. RabbitMQ
  rabbitmq: # Tên service là rabbitmq
    image: rabbitmq:3-management
    container_name: flashsale_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - flashsale-network

volumes:
  mongo_data:
  rabbitmq_data:

networks:
  flashsale-network:
    driver: bridge